// AUTO-GENERATED by tools/gen_canonical_ig.py — do not hand-edit.
// Source: imscrbgrmr/canonical_primitives.py + navigators/cl8nk_navigator.py
// Regenerate after any change to the alphabet, the ordinals or the
// CL8NK formulae. `make ordinals` guards ordinal drift against Lean.
#![allow(dead_code)]

/// The twelve axis marks, in canonical order.
pub static PRIMITIVE_ORDER: [&str; 12] = ["⊢", "⊣", "≻", "≺", "⋈", "⊤", "∈", "∋", "⊙", "⊥", "⊞", "⊡"];

/// Axis mark to the axis's name.
pub static PRIMITIVE_NAMES: [(&str, &str); 12] = [
    ("⊢", "Dimensionality"),
    ("⊣", "Topology"),
    ("≻", "Relational"),
    ("≺", "Polarity"),
    ("⋈", "Fidelity"),
    ("⊤", "Kinetics"),
    ("∈", "Scope"),
    ("∋", "Composition"),
    ("⊙", "Criticality"),
    ("⊥", "Chirality"),
    ("⊞", "Stoichiometry"),
    ("⊡", "Winding"),
];

/// Each axis's values, in ordinal order.
pub static CANONICAL_VALUES: [(&str, &[&str]); 12] = [
    ("⊢", &["𐑛", "𐑨", "𐑼", "𐑦"]),
    ("⊣", &["𐑡", "𐑰", "𐑥", "𐑶", "𐑸"]),
    ("≻", &["𐑩", "𐑑", "𐑽", "𐑾"]),
    ("≺", &["𐑗", "𐑿", "𐑬", "𐑯", "𐑹"]),
    ("⋈", &["𐑱", "𐑞", "𐑐"]),
    ("⊤", &["𐑘", "𐑤", "𐑧", "𐑪", "𐑺"]),
    ("∈", &["𐑚", "𐑔", "𐑲"]),
    ("∋", &["𐑝", "𐑜", "𐑠", "𐑵"]),
    ("⊙", &["𐑢", "⊙", "𐑮", "𐑻", "𐑣"]),
    ("⊥", &["𐑓", "𐑒", "𐑖", "𐑫"]),
    ("⊞", &["𐑙", "𐑕", "𐑳"]),
    ("⊡", &["𐑷", "𐑴", "𐑭", "𐑟"]),
];

/// Value to its ordinal rank. Not every axis is consecutive:
/// Kinetics puts many-body localisation at 4.5, above trapped.
pub static ORDINALS: [(&str, &[(&str, f32)]); 12] = [
    ("⊢", &[("𐑛", 1.0), ("𐑨", 2.0), ("𐑼", 3.0), ("𐑦", 4.0)]),
    ("⊣", &[("𐑡", 1.0), ("𐑰", 2.0), ("𐑥", 3.0), ("𐑶", 4.0), ("𐑸", 5.0)]),
    ("≻", &[("𐑩", 1.0), ("𐑑", 2.0), ("𐑽", 3.0), ("𐑾", 4.0)]),
    ("≺", &[("𐑗", 1.0), ("𐑿", 2.0), ("𐑬", 3.0), ("𐑯", 4.0), ("𐑹", 5.0)]),
    ("⋈", &[("𐑱", 1.0), ("𐑞", 2.0), ("𐑐", 3.0)]),
    ("⊤", &[("𐑘", 1.0), ("𐑤", 2.0), ("𐑧", 3.0), ("𐑪", 4.0), ("𐑺", 4.5)]),
    ("∈", &[("𐑚", 1.0), ("𐑔", 2.0), ("𐑲", 3.0)]),
    ("∋", &[("𐑝", 1.0), ("𐑜", 2.0), ("𐑠", 3.0), ("𐑵", 4.0)]),
    ("⊙", &[("𐑢", 1.0), ("⊙", 2.0), ("𐑮", 2.33), ("𐑻", 2.67), ("𐑣", 3.0)]),
    ("⊥", &[("𐑓", 1.0), ("𐑒", 2.0), ("𐑖", 3.0), ("𐑫", 4.0)]),
    ("⊞", &[("𐑙", 1.0), ("𐑕", 2.0), ("𐑳", 3.0)]),
    ("⊡", &[("𐑷", 1.0), ("𐑴", 2.0), ("𐑭", 3.0), ("𐑟", 4.0)]),
];

/// Per-axis distance weights.
pub static WEIGHTS: [(&str, f32); 12] = [
    ("⊢", 1.0),
    ("⊣", 1.0),
    ("≻", 1.0),
    ("≺", 1.0),
    ("⋈", 1.0),
    ("⊤", 1.0),
    ("∈", 1.0),
    ("∋", 1.0),
    ("⊙", 1.0),
    ("⊥", 0.8),
    ("⊞", 1.0),
    ("⊡", 0.7),
];

/// CL8NK formula fragments: axis -> value -> (fragment, atom, proximity).
/// An empty atom means the value promotes no atom.
pub static CL8NK_FORMULAE: [(&str, &[(&str, &str, &str, &str)]); 12] = [
    ("⊢", &[("𐑦", "V = L(x) ∧ selfmodel(x) ∧ x ∈ V", "HOLOGRAPHIC_STATE", "match"), ("𐑼", "∀n∃y( y ∈ x ∧ rank(y) > n )", "", "close"), ("𐑨", "dim(x) = 2 ∧ sur(x)", "", "distant"), ("𐑛", "dim(x) = 0 ∧ fin(x)", "", "distant")]),
    ("⊣", &[("𐑸", "bound_⊙(a, f) ∧ Refl(a, f) ∧ holo(x, a)", "HOLOBOUND", "match"), ("𐑥", "cross(x, y) ∧ ¬ meet(x, y)", "", "close"), ("𐑶", "x ⊠ y ∧ irreducible(x, y)", "", "distant"), ("𐑡", "graph(x) ∧ branch(x)", "", "distant"), ("𐑰", "x ⊆ y ∧ cont(y)", "", "distant")]),
    ("≻", &[("𐑾", "lr⇔(x, y) ∧ Θ(x, y) ∧ ¬ Θ(y, x)", "LR_DUAL", "match"), ("𐑽", "f ⊣ g ∧ L Adj(f, g)", "", "close"), ("𐑑", "Fun(x, y) ∧ Nat(y, z) → Fun(x, z)", "", "distant"), ("𐑩", "x ↑ y ∧ ¬(y ↑ x)", "", "distant")]),
    ("≺", &[("𐑹", "ℤ₂(x) ∧ ∀g∈G( gx = x ) ∧ μ∘δ = id", "PM_Z2", "match"), ("𐑿", "|ψ⟩ = Σ c_i |e_i⟩", "", "close"), ("𐑬", "ℤ₂(x) ∧ ¬(x = -x)", "", "close"), ("𐑯", "∀g∈G( gx = x )", "", "distant"), ("𐑗", "¬∃sym(x)", "", "distant")]),
    ("⋈", &[("𐑐", "ℏ(x) ∧ [x, p] = iℏ", "", "match"), ("𐑞", "Tr(ρ²) < 1 ∧ ρ = Σ p_i |i⟩⟨i|", "", "close"), ("𐑱", "P(x) ∈ {0,1} ∧ det(x)", "", "distant")]),
    ("⊤", &[("𐑧", "τ ≫ T ∧ eq(x) ∧ gate_open(x)", "", "match"), ("𐑤", "τ ∼ T ∧ noisy(x)", "", "close"), ("𐑘", "τ ≪ T ∧ ∂_t x = f(x)", "", "distant"), ("𐑪", "τ = ∞ ∧ ord(x)", "", "distant"), ("𐑺", "τ = ∞ ∧ dis(x) ∧ MBL", "", "distant")]),
    ("∈", &[("𐑲", "∀y( y ⊂ x → |y| < |x| )", "", "match"), ("𐑔", "∃y∈x( |y| ∼ |x| )", "", "close"), ("𐑚", "∀y∈x( |y| < |x| )", "", "distant")]),
    ("∋", &[("𐑵", "f → all(x) ∧ broadcast(x, f)", "BROADCAST_TRANSCENDENCE", "match"), ("𐑠", "seq!(f, g) ∧ ⟨→⟩(f, g, τ) ∧ ¬ ⟨→⟩(g, f, τ)", "SEQAX", "close"), ("𐑜", "f ∨ g ∨ h", "", "distant"), ("𐑝", "f ∧ g ∧ h", "", "distant")]),
    ("⊙", &[("⊙", "ξ → ∞ ∧ μ∘δ = id", "PHI_C", "match"), ("𐑮", "ξ ∈ ℂ ∧ Im(ξ) → ∞", "", "close"), ("𐑻", "H(λ) non-Herm ∧ det(H - λI) = 0 ∧ ∂_λ H = 0", "", "distant"), ("𐑣", "ξ → ∞ ∧ chaotic(x)", "", "distant"), ("𐑢", "¬∃ξ( diverges(ξ) )", "", "distant")]),
    ("⊥", &[("𐑫", "∀n∃φ( rank(φ) > n ∧ φ fixed by μ∘δ ∧ φ ∈ V )", "ETERNAL_FIXEDPOINT", "match"), ("𐑖", "∃y∃z( y ∈ x ∧ z ∈ y ∧ ¬ z ∈ x ∧ rank(z) < rank(y) )", "TEMPD2", "close"), ("𐑒", "∃y( P(y) ↔ P(S²(y)) )", "", "distant"), ("𐑓", "∀x( P(x) ↔ P(S(x)) )", "", "distant")]),
    ("⊞", &[("𐑳", "∃a∈A∃b∈B( type(a) ≠ type(b) )", "", "match"), ("𐑕", "∀a∈A∀b∈B( type(a) = type(b) )", "", "close"), ("𐑙", "|A| = 1 ∧ |B| = 1", "", "distant")]),
    ("⊡", &[("𐑟", "Braid(σ_i) ∧ R_matrix ≠ 0 ∧ nonAbelian(x)", "BRAID_TRANSCENDENCE", "match"), ("𐑭", "∮_γ A = 2πn ∧ n ∈ ℤ ∧ wind(γ) ≠ 0", "ZWIND", "close"), ("𐑴", "∮_γ A = nπ ∧ n ∈ ℤ₂", "", "distant"), ("𐑷", "∮_γ dx = 0", "", "distant")]),
];


/// The axis a value belongs to, or None if the value is off every axis.
pub fn axis_of(value: &str) -> Option<&'static str> {
    for (axis, vals) in CANONICAL_VALUES.iter() {
        for v in vals.iter() {
            if *v == value { return Some(axis); }
        }
    }
    None
}

/// A value's ordinal rank on its axis.
pub fn ordinal_of(axis: &str, value: &str) -> Option<f32> {
    for (a, rows) in ORDINALS.iter() {
        if *a != axis { continue; }
        for (v, o) in rows.iter() {
            if *v == value { return Some(*o); }
        }
    }
    None
}

/// The name of an axis.
pub fn name_of(axis: &str) -> Option<&'static str> {
    for (a, n) in PRIMITIVE_NAMES.iter() {
        if *a == axis { return Some(n); }
    }
    None
}

/// The distance weight of an axis.
pub fn weight_of(axis: &str) -> Option<f32> {
    for (a, w) in WEIGHTS.iter() {
        if *a == axis { return Some(*w); }
    }
    None
}

/// The CL8NK fragment, promoted atom and proximity for a value.
pub fn formula_of(axis: &str, value: &str) -> Option<(&'static str, &'static str, &'static str)> {
    for (a, rows) in CL8NK_FORMULAE.iter() {
        if *a != axis { continue; }
        for (v, frag, atom, prox) in rows.iter() {
            if *v == value { return Some((frag, atom, prox)); }
        }
    }
    None
}

/// Index of an axis in canonical order.
pub fn axis_index(axis: &str) -> Option<usize> {
    let mut i = 0;
    while i < PRIMITIVE_ORDER.len() {
        if PRIMITIVE_ORDER[i] == axis { return Some(i); }
        i += 1;
    }
    None
}
