// ─── Cross-Dialect Ruleset Definitions ────────────────────────
// Generated by ⊙perator — implements U₀ through U₈₇.
// U₀–U₁₁: hand-crafted canonical + Phase I dialects (exact gate/tier strings preserved).
// U₁₂–U₈₇: Phase III expansion (59 dialects) — bridged to dialect_expansion.rs.
//
// U₈ (chirality_first), U₉ (scope_dialect), U₁₀ (triple_criticality) added
// 2026-06-16, ported from imscribing_grammar/scripts/new_dialects.py.
// u8_max raised: 11→87 on 2026-07-04 alongside the dialect_expansion bridge.
//
// Author: Lando⊗⊙perator
// Updated: 2026-07-06 — dialect_expansion bridge (the 88 were always here, just invisible)

use crate::dialect_expansion::{all_dialects, DIALECT_COUNT};
use alloc::string::String;
use alloc::string::ToString;
use alloc::format;

// ═══════════════════════════════════════════════════════════════
// BRIDGE: EXPANSION UNIVERSE DATA ACCESS
// ═══════════════════════════════════════════════════════════════

/// Number of hand-crafted dialects (0–11) whose display strings we preserve as-is.
const HAND_CRAFTED_COUNT: u8 = 12;

/// Check whether an index is in the expansion range.
fn is_expansion(u: u8) -> bool {
    u >= HAND_CRAFTED_COUNT && (u as usize) < DIALECT_COUNT
}

/// Check whether an index is out of range entirely.
fn is_out_of_range(u: u8) -> bool {
    (u as usize) >= DIALECT_COUNT
}

/// Format a u8 as Unicode subscript digits (U+2080..U+2089).
fn subscript_u8(u: u8) -> String {
    if u == 0 {
        return "\u{2080}".to_string();
    }
    let mut buf = [0u8; 3]; // max two-digit decimal
    let mut n = u;
    let mut pos = 0;
    while n > 0 {
        buf[pos] = n % 10;
        n /= 10;
        pos += 1;
    }
    let mut out = String::new();
    for i in (0..pos).rev() {
        let digit = buf[i];
        out.push(char::from_u32(0x2080u32 + digit as u32).unwrap());
    }
    out
}

// ═══════════════════════════════════════════════════════════════
// PARSE
// ═══════════════════════════════════════════════════════════════

/// Parse a dialect designator. Accepts "U_0".."U_99" and "U₀".."U₉₉"
/// (multi-digit, ASCII or Unicode subscript).
pub fn parse_dialect(s: &str) -> Option<u8> {
    // Try ASCII "U_<digits>"
    if let Some(rest) = s.strip_prefix("U_") {
        if !rest.is_empty() && rest.bytes().all(|b| b.is_ascii_digit()) {
            return rest.parse::<u8>().ok();
        }
    }
    // Try Unicode subscript digits U+2080..U+2089, one or more, after a leading 'U'
    let mut chars = s.chars();
    if chars.next() != Some('U') {
        return None;
    }
    let rest: alloc::string::String = chars.collect();
    if rest.is_empty() || !rest.chars().all(|c| c >= '\u{2080}' && c <= '\u{2089}') {
        return None;
    }
    let mut val: u32 = 0;
    for c in rest.chars() {
        val = val * 10 + (c as u32 - 0x2080);
    }
    u8::try_from(val).ok()
}

// ═══════════════════════════════════════════════════════════════
// DISPLAY / ASCII / NAME / DESCRIPTION / GATES / O_INF
// ═══════════════════════════════════════════════════════════════

/// Return the display name for a dialect index (Unicode subscript).
/// For U₀–U₁₁: hand-crafted. For U₁₂–U₈₇: generated from dialect data.
pub fn dialect_display(u: u8) -> String {
    if is_out_of_range(u) {
        return "U?".to_string();
    }
    format!("U{}", subscript_u8(u))
}

/// Return the ASCII-safe name: "U_0" through "U_87".
pub fn dialect_ascii(u: u8) -> String {
    if is_out_of_range(u) {
        return "U_?".to_string();
    }
    format!("U_{}", u)
}

/// Return the canonical name for a dialect.
pub fn dialect_name(u: u8) -> &'static str {
    match u {
        0 => "canonical",
        1 => "low_gate",
        2 => "strict_frobenius",
        3 => "inverted_gates",
        4 => "no_ordering",
        5 => "high_gate",
        6 => "winding_first",
        7 => "t_structural",
        8 => "chirality_first",
        9 => "scope_dialect",
        10 => "triple_criticality",
        11 => "triple_criticality_gapped",
        _ if is_expansion(u) => {
            let unis = all_dialects();
            unis[u as usize].name
        }
        _ => "unknown",
    }
}

/// Return the description for a dialect.
pub fn dialect_description(u: u8) -> &'static str {
    match u {
        0 => "Our dialect: Frobenius then self-modeling then winding seal",
        1 => "Lowered thresholds: directional parity suffices, any criticality",
        2 => "Frobenius gated by quantum fidelity (f=pc), not algebraic parity",
        3 => "Self-modeling precedes Frobenius: consciousness first",
        4 => "All three gates fully independent — parallel dialect",
        5 => "Strictest possible: maximally wound, self-modeling, parity-perfect",
        6 => "Topological order: winding first, then self-modeling, Frobenius last",
        7 => "Time as geometry: T=lim(D,Th,R,Gm,Ph) instead of dynamic T",
        8 => "Memory before closure: G1=⊥≥𐑖 (two-step Markov), then self-model, \
              then winding. T-constitution is ceiling-mode (T_CEILING), not \
              exact-equality.",
        9 => "Universality first: G1=∈≥𐑲 (maximal range) — parochial systems \
              stay plain no matter how structured. G2=self-model, G3=winding. \
              T-constitution is ceiling-mode (T_CEILING), not exact-equality.",
        10 => "Criticality is everything: all three gates are the SAME primitive \
               (⊙) at escalating thresholds (𐑢 / ⊙ / 𐑣). <, ⊡, and the rest are \
               descriptive, not gating. T-constitution is ceiling-mode (T_CEILING).",
        11 => "Same as U10, but the kinetics ceiling admits trapped/gapped spectra \
               (⊤=𐑪), not just slow ones (⊤=𐑧) — the temporal-closure condition \
               for a mass-gap claim should not exclude the gap itself.",
        _ if is_expansion(u) => {
            let unis = all_dialects();
            unis[u as usize].description
        }
        _ => "Unknown dialect",
    }
}

/// Format a single GateSpec into a human-readable string fragment.
fn gate_spec_fmt(g: &crate::dialect_expansion::GateSpec) -> String {
    // A threshold is a value on that mark's axis, so it prints as the Shavian
    // letter that value is, not as the ordinal number standing behind it: the
    // first value on the axis that meets the bar.
    let table = crate::catalog::ordinal_table(g.prim);
    let value = table
        .iter()
        .find(|v| v.ordinal() >= g.min_ord)
        .or_else(|| table.last());
    match value {
        Some(v) => format!("{}≥{}", g.prim, v.glyph()),
        None => format!("{}≥{}", g.prim, g.min_ord),
    }
}

/// Return the gate summary string for a dialect.
pub fn dialect_gates(u: u8) -> String {
    // Every dialect carries its gates as GateSpecs in the marks, so every
    // dialect is printed from them. The hand-written strings that used to sit
    // here for the first twelve were a second notation: Phi, Phc, Omega, f, Gm
    // for the marks, and the English names of Shavian letters where the letters
    // belong. There is one notation and these are not it.
    if is_out_of_range(u) {
        return "Unknown gates".to_string();
    }
    let unis = all_dialects();
    let uni = &unis[u as usize];
    format!(
        "G1:{}  G2:{}  G3:{}  [{}]  T:{}",
        gate_spec_fmt(&uni.g1),
        gate_spec_fmt(&uni.g2),
        gate_spec_fmt(&uni.g3),
        if uni.gate_ordering { "seq" } else { "par" },
        if uni.t_entries.is_empty() { "none" } else { "dynamic" }
    )
}

/// Return O_∞ fraction description for a dialect.
pub fn dialect_o_inf(u: u8) -> &'static str {
    match u {
        0 => "~8%",  1 => "~30%", 2 => "~3.3%", 3 => "~8%",
        4 => "~8%",  5 => "~3%",  6 => "~8%",   7 => "~8%", 8 => "20%", 9 => "13.3%",
        10 => "16%", 11 => "16%",
        _ if is_expansion(u) => "compute",
        _ => "?",
    }
}

// ═══════════════════════════════════════════════════════════════
// DYNAMIC GATE EVALUATION (for expansion dialects)
// ═══════════════════════════════════════════════════════════════

use crate::imas_ig::{IgPrim, IgTuple};

/// Map a GateSpec primitive string to the corresponding IgPrim value from an IgTuple.
/// Returns None for unrecognized primitive names.
pub fn prim_from_name(name: &str, ig: &IgTuple) -> Option<IgPrim> {
    match name {
        "≺" => Some(ig.p),
        "⊙" => Some(ig.phi),
        "⊡" => Some(ig.omega),
        "⊥" => Some(ig.h),
        "∈" => Some(ig.g),
        "⊣" => Some(ig.t),
        "≻" => Some(ig.r),
        "⋈" => Some(ig.f),
        "⊤" => Some(ig.k),
        "⊢" => Some(ig.d),
        "⊞" => Some(ig.s),
        "∋" => Some(ig.c),
        _ => None,
    }
}

/// Evaluate a single gate spec against an IG tuple.
/// Returns (pass, prim_value_ordinal, prim_name).
pub fn eval_gate_spec(
    spec: &crate::dialect_expansion::GateSpec,
    ig: &IgTuple,
) -> (bool, f32, &'static str) {
    let prim = prim_from_name(spec.prim, ig);
    match prim {
        Some(pv) => {
            let ord = pv.ordinal();
            (ord >= spec.min_ord, ord, pv.glyph())
        }
        None => (false, 0.0, "?"),
    }
}

/// Whether a dialect is hand-crafted and uses hardcoded gate logic in main.rs.
pub fn is_hand_crafted(u: u8) -> bool {
    u < HAND_CRAFTED_COUNT
}

/// The maximum valid dialect index (inclusive).
pub fn max_dialect() -> u8 {
    (DIALECT_COUNT - 1) as u8
}
